site_name: TEST-NAD
site_url:
theme:
  name: material

plugins:
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: ru
          name: Русский
          build: true

nav:
  - Home: index.md
  - Contributing: CONTRIBUTING.md