site_name: TEST-NAD
theme:
  name: material

nav:
  - English:
      - Home: en/index.md
      - Contributing: en/CONTRIBUTING.md
  - Русский:
      - Главная: ru/index.md
      - Вклад: ru/CONTRIBUTING.md

plugins:
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: ru
          name: Русский
          build: true
