site_name: TEST-NAD
theme:
  name: material

plugins:
  - i18n:
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: ru
          name: Русский
          build: true

nav:
  - Home: README.md
  - Contributing: CONTRIBUTING.md