[project]
name = "ptnad"
version = "0.1.0"
description = "Python library for interacting with the PT NAD API"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
authors = [
    { name = "Andrey Tyulenev" }
]
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
]

[project.optional-dependencies]
docs = [
    "mkdocs>=1.5.3",
    "mkdocs-material>=9.5.10",
    "mkdocs-i18n-plugin",
    "mkdocs-localsearch"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
