[project]
name = "ptnad-client-test"
version = "0.1.0"
description = "Python library for interacting with the PT NAD API"
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "None" }]
dependencies = [
    "requests>=2.32.3",
]

[project.urls]
Homepage = "https://github.com/Security-Experts-Community/ptnad"
Documentation = "https://security-experts-community.github.io/ptnad"
Repository = "https://github.com/Security-Experts-Community/ptnad"
Issues = "https://github.com/Security-Experts-Community/ptnad/issues"

[dependency-groups]
dev = [
    "black>=24.10.0",
    "isort>=5.13.2",
    "mypy>=1.14.1",
]
docs = [
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.7",
    "termynal>=0.13.0",
]

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["ptnad"]

[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"

[tool.mypy]
strict = true
ignore_missing_imports = true

[tool.ruff]
lint.select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
lint.ignore = ["E501"]
line-length = 120
target-version = "py311"
